services:
  discord-bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_1_ID=${CHANNEL_1_ID}
      - CHANNEL_2_ID=${CHANNEL_2_ID}
      - WEBHOOK_1_URL=${WEBHOOK_1_URL}
      - WEBHOOK_2_URL=${WEBHOOK_2_URL}
    volumes:
      - ./logs:/app/logs
